name: Build and Test

on: [push, pull_request]

jobs:
  build-linux:
    env:
      dependencies: |
        automake libtool gcc bc libjemalloc1 libjemalloc-dev    \
        libssl-dev llvm-dev libelf-dev libnuma-dev libpcap-dev  \
        ninja-build selinux-policy-dev
      deb_dependencies: |
        linux-headers-$(uname -r) build-essential fakeroot devscripts equivs
      AFXDP:       ${{ matrix.afxdp }}
      ASAN:        ${{ matrix.asan }}
      CC:          ${{ matrix.compiler }}
      DEB_PACKAGE: ${{ matrix.deb_package }}
      DPDK:        ${{ matrix.dpdk }}
      DPDK_SHARED: ${{ matrix.dpdk_shared }}
      KERNEL:      ${{ matrix.kernel }}
      KERNEL_LIST: ${{ matrix.kernel_list }}
      LIBS:        ${{ matrix.libs }}
      M32:         ${{ matrix.m32 }}
      OPTS:        ${{ matrix.opts }}
      TESTSUITE:   ${{ matrix.testsuite }}

    name: linux ${{ join(matrix.*, ' ') }}
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        include:
          - compiler:     clang
            testsuite:    test
            kernel:       3.16
            asan:         asan

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: update PATH
      run:  |
        echo "$HOME/bin"        >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: create ci signature file for the dpdk cache key
      if:   matrix.dpdk != '' || matrix.dpdk_shared != ''
      # This will collect most of DPDK related lines, so hash will be different
      # if something changed in a way we're building DPDK including DPDK_VER.
      # This also allows us to use cache from any branch as long as version
      # and a way we're building DPDK stays the same.
      run:  |
        grep -irE 'RTE_|DPDK|meson|ninja' -r .ci/ > dpdk-ci-signature
        cat dpdk-ci-signature

    - name: cache
      if:   matrix.dpdk != '' || matrix.dpdk_shared != ''
      uses: actions/cache@v2
      env:
        matrix_key: ${{ matrix.dpdk }}${{ matrix.dpdk_shared }}
        ci_key:     ${{ hashFiles('dpdk-ci-signature') }}
      with:
        path: dpdk-dir
        key:  ${{ env.matrix_key }}-${{ env.ci_key }}

    - name: update APT cache
      run:  sudo apt update || true
    - name: install common dependencies
      if:   matrix.deb_package == ''
      run:  sudo apt install -y ${{ env.dependencies }}
    - name: install dependencies for debian packages
      if:   matrix.deb_package != ''
      run:  sudo apt install -y ${{ env.deb_dependencies }}
    - name: install libunbound libunwind
      if:   matrix.m32 == ''
      run:  sudo apt install -y libunbound-dev libunwind-dev

    - name: prepare
      run:  ./.ci/linux-prepare.sh

    - name: build
      run:  ./.ci/linux-build.sh

    - name: upload deb packages
      if:   matrix.deb_package != ''
      uses: actions/upload-artifact@v2
      with:
        name: deb-packages
        path: '/home/runner/work/ovs/*.deb'

    - name: copy logs on failure
      if: failure() || cancelled()
      run: |
        # upload-artifact@v2 throws exceptions if it tries to upload socket
        # files and we could have some socket files in testsuite.dir.
        # Also, upload-artifact@v2 doesn't work well enough with wildcards.
        # So, we're just archiving everything here to avoid any issues.
        mkdir logs
        cp config.log ./logs/
        cp -r ./*/_build/sub/tests/testsuite.* ./logs/ || true
        tar -czvf logs.tgz logs/

    - name: upload logs on failure
      if: failure() || cancelled()
      uses: actions/upload-artifact@v2
      with:
        name: logs-linux-${{ join(matrix.*, '-') }}
        path: logs.tgz
